"""add web push fields to notification_preferences

Revision ID: 6f16e06ade2e
Revises: c444c92d9a8e
Create Date: 2025-04-19 14:17:52.460071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f16e06ade2e'
down_revision: Union[str, None] = 'c444c92d9a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('push_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notification_preferences', sa.Column('push_endpoint', sa.String(), nullable=True))
    op.add_column('notification_preferences', sa.Column('push_p256dh', sa.String(), nullable=True))
    op.add_column('notification_preferences', sa.Column('push_auth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'push_auth')
    op.drop_column('notification_preferences', 'push_p256dh')
    op.drop_column('notification_preferences', 'push_endpoint')
    op.drop_column('notification_preferences', 'push_enabled')
    # ### end Alembic commands ###
