name: Deploy fastapi app to AWS Lambda
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Package FastAPI for Lambda
        run: |
            mkdir -p package
            pip install --target ./package  -r requirements.txt --no-cache-dir
            pip install --target ./package  bcrypt
            (cd package; zip ../aws_lambda_artifact.zip -r .)
            cp -r app package/            
            cp -r alembic package/
            cp -r alembic.ini package/
            cd package && zip -r ../aws_lambda_artifact.zip .
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code \
            --function-name FastAPI-Lambda \
            --zip-file fileb://aws_lambda_artifact.zip